# ===========================
# FRONTEND DOCKERFILE
# ===========================

# Stage 1 — Build React App
FROM node:18 AS build
WORKDIR /app

RUN apt-get update && apt-get install -y git

# Clone your TravelForge Repo
RUN git clone https://github.com/Bhavya33060/TravelForge .

RUN npm install
RUN npm run build

# Stage 2 — Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
